server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa
    username: root
    password: xdxx050204
  data:
    redis:
      host: 192.168.217.131
      password: 123456
      port: 6379
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数
          max-idle: 8   # 连接池中的最大空闲连接
          min-idle: 0   # 连接池中的最小空闲连接
          max-wait: 60   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      connect-timeout: 360
  rabbitmq:
    host: 192.168.217.131
    port: 5672
    stream:
      username: admin
      password: admin123
      virtual-host: /

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 事务管理配置

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800  # 7day
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

spx:
    minio:
      endpointUrl: http://192.168.217.131:9000
      accessKey: admin
      secreKey: admin123
      bucketName: oa-bucket



